version: '3.1'

volumes:
  mongo_data:

services:
  api:
    build: ./api/
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api/src:/api/src
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "sample_user"
      MONGO_INITDB_ROOT_PASSWORD: "ChangeMe123"
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"